### ISSUE TITLE
导出的java 文件 有语法错误

### ISSUE THREAD

**Issue by niu56798405** [Ourpalm/behaviac#1]
比如 在编辑器中 为 agent 增加一个  selectTarget 方法 参数 int skillId  返回 long 数组  生成的 的代码 返回泛型 是不正确的.

另外有多余的 , (逗号)

	public static IMethod CreateMemberMethod_SELECTSKILL() {
		return new CAgentMethod0<Integer,>((Agent _agent,)->{ return ((BaseAgent)_agent).selectSkill();}, new ClassInfo(Integer.class), new ClassInfo[]{  });
	}
	public ArrayList<List`1> selectTarget(Integer skillId)

**Comment by ctemple** [comment]
已修复

**Comment by niu56798405** [comment]
thanks



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "templar1982"<notifications@github.com&gt;; 
发送时间: 2021年1月7日(星期四) 下午5:24
收件人: "Ourpalm/behaviac";
抄送: "Author";
主题: Re: [Ourpalm/behaviac] 导出的java 文件 有语法错误 (#1)





 
已修复
 
&mdash;
