### ISSUE TITLE
编辑器怎么导出java胶水代码

### ISSUE THREAD

**Issue by yangzhy-scott** [Ourpalm/behaviac#2]

**Comment by ctemple** [comment]
创建一个java工程，"代码生成位置"里会生成 BehaviorLoaderImplement.java以及各个Agent的框架代码。行为树目前只支持导出xml，不支持导出为json或者java代码。
举个例子，工程目录G:\behaviorTest，导出的以上代码，在目录G:\behaviorTest\exported\behaviac_generated\types
